# When `true` will include referenced resources using
# the `existing` keyword in the resources list
includeExistingResources: true

# Metadata definition keyword used for module
# metadata
metaKeyword: "moduleDocs"

# Include the parameters section
includeParameters: true

# Include the code example /usage section
includeUsage: true

# Include the list of resources
includeResources: true

# Inlude the outputs section
includeOutputs: true

# Include referenced resources
includeReferencedResources: true

# Section order for the generated document
sectionOrder:
  - title
  - description
  - usage
  - referencedResources
  - parameters
  - resources
  - outputs
  - parameterReferences # This is the list of complex parameters and allow values

# Do not generate versioned output folders
disableVersioning: false

# Configuration for individual providers
formatters:
  docusaurus:
    # Do not add page tags (resource providers)
    addPageTags: true
  markdown:
    # input values for usage examples
    usage:
      # determins if the usage examples uses "br" or "ts".
      # accepted values are 'local' and 'registry'
      moduleType: local
      # the alias used. Same as "moduleAliases" in bicepconfig.json
      moduleAlias: IacModules
